config/routes.rb
Rails.application.routes.draw do
	namespace 'api' do
		namespace 'v1' do
			resources :categories
			resources :brands
			resources :products
		end
	end
devise_for :users
resources :products
resources :brands
resources :categories
resources :users
root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :product, :dependent => :delete_all
	acts_as_paranoid
	has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" },
	:path => ':rails_root/public/images/brands/:id-:basename-:style.:extension',
	:url => '/images/brands/:id-:basename-:style.:extension'
	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
	validates :name, presence: true
	validates :picture, attachment_presence: true
	#Search method
	def self.search(search)
		where("name LIKE ?", "%#{search}%") 
	end
	def picture_url
		picture.url(:thumb)
	end
end

app/controllers/api/v1/brands_controller.rb
module Api
	module V1
		class BrandsController < ApplicationController   
			def index
				brands = Brand.order('created_at DESC');
				render json: {status: 'SUCCESS', message:'Objetos carregados', data:brands, }, :methods => [:picture_url] ,status: :ok	
			end
			def destroy
				brand = Brand.all
				brand = Brand.where(id: params[:id]).first
				if brand.destroy
					redirect_to brands_url
				end
			end
		end
	end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :index
  before_action :authenticate_user!


  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
    if params[:search]
      @brands = Brand.search(params[:search]).order("created_at DESC")
    else
      @brands = Brand.all.order('created_at DESC')
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
   
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)
    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    render json: @brands
    @products = Product.all
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :picture, :search)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_edit.html.erb
    <p class='form-p' style='padding-left: 5%'>Atualizar Marca</p>
    <%= form_with(model: brand, local: true, html: { multipart: true }) do |form| %>
    <%= form.label 'Nome:' %>
    <br>
    <%= form.text_field :name, id: :product_name %>
    <br>
    <%= form.label 'Foto:'%> 
    <br>
    <%= form.file_field :picture %>
    <br>
    <div class="wrapper">
      <span class="group-btn">     
        <%= form.submit 'Atualizar Marca', :class => 'btn btn-success' %>
        <%= link_to 'Voltar', brands_path, :class => 'btn btn-warning' %>
      </div>
    </span>
    <% end %> 

app/views/brands/_form.html.erb
    <p class='form-p' style='padding-left: 5%'>Cadastro Marca</p>
    <%= form_with(model: brand, local: true, html: { multipart: true }) do |form| %>
    <%= form.label 'Nome:' %>
    <br>
    <%= form.text_field :name, id: :product_name %>
    <br>
    <%= form.label 'Foto:'%> 
    <br>
    <%= form.file_field :picture %>
    <br>
    <div class="wrapper">
      <span class="group-btn">     
        <%= form.submit 'Cadastrar Marca', :class => 'btn btn-success' %>
        <%= link_to 'Voltar', brands_path, :class => 'btn btn-warning' %>
      </div>
    </span>
    <% end %> 

app/views/brands/edit.html.erb
<body class='bg-new'>
 <div class='container-fluid'>
        <div class='row' >    
          <nav class='navbar menu' align='center' >
            <ul>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -4%"><a href='#'>Produtos</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_product_path %></li>
                  <li><%= link_to 'Ver todos', products_path %></li>
                </ul>
              </li>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%"><a href='#'>Marcas</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_brand_path %></li>
                  <li><%= link_to 'Ver todos', brands_path %></li>
                </ul></li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%" ><a href='#'>Categorias</a>
                  <ul>
                    <li><%= link_to 'Cadastrar', new_category_path %></li>
                    <li><%= link_to 'Ver todos', categories_path %></li>
                  </ul>
                </li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%">
                  <%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
                
              </nav>
            </div>
          </div>
        </div>
      </div>

	<div class='container-fluid' %>
		<ul class='errors'>
		<% @brand.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
		<div class='row'>
			<div class='col-lg-4 col-md-4 col-sm-4 form-border' align='center' style=' padding-bottom: 1%; float:none; margin: 0 auto;'>
				<%= render 'edit', brand: @brand %>
			</div>
		</div>
	</div>
</body>

app/views/brands/index.html.erb
<body>
  <div class='container-fluid'>
    <div class='row' align='center'>    
      <nav class='navbar menu' >
        <ul>
          <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -4%"><a href='#'>Produtos</a>
            <ul>
              <li><%= link_to 'Cadastrar', new_product_path %></li>
              <li><%= link_to 'Ver todos', products_path %></li>
            </ul>
          </li>
          <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%"><a href='#'>Marcas</a>
            <ul>
              <li><%= link_to 'Cadastrar', new_brand_path %></li>
              <li><%= link_to 'Ver todos', brands_path %></li>
            </ul></li>
            <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%" ><a href='#'>Categorias</a>
              <ul>
                <li><%= link_to 'Cadastrar', new_category_path %></li>
                <li><%= link_to 'Ver todos', categories_path %></li>
              </ul>
            </li>
            <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%">
              <%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>

            </nav>
          </div>
        </div>
      </div>
    </div>


    <div class="container-fluid">
      <h2 style='text-align: center'>Marcas</h2>
    </div>

    <!-- Table -->

    <div class="table-responsive" style="width: 70%; margin-left: auto; margin-right: auto;">
      <div ng-app='myApp' ng-controller='ListBrandCtrl'>
        <div align='center' style='min-width: 70%;'>
         <input type="text" ng-model="agoravai" class='form-control' style='width: 25%; text-align: center' placeholder="Informe o nome ...">
       </div>
       <table class="table table-striped">
        <thead>
          <tr>
            <th> Foto </th>
            <th> Nome </th>
            <th></th>
          </tr>
        </thead>
        <tbody ng-repeat="brands in brand | filter:{name:agoravai}">
          <td><img src='{{brands.picture_url}}'></td>
          <td>{{brands.name}}</td>
          <td>
            <a href='brands/{{brands.id}}' class='btn btn-info'>Ver</a>
            <a data-method='delete' data-confirm='Você tem certeza?' href='/api/v1/brands/{{brands.id}}' class='btn btn-danger'> Deletar </a>
          </td>
        </tbody>
      </table>
    </div>
    <%= link_to 'Nova Marca', new_brand_path, :class => 'btn btn-primary' %>
  </div>
</div>
</div>
</div>

app/views/brands/new.html.erb
<body class='bg-new'>
	 <div class='container-fluid'>
        <div class='row' align='center'>    
          <nav class='navbar menu' >
            <ul>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -4%"><a href='#'>Produtos</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_product_path %></li>
                  <li><%= link_to 'Ver todos', products_path %></li>
                </ul>
              </li>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%"><a href='#'>Marcas</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_brand_path %></li>
                  <li><%= link_to 'Ver todos', brands_path %></li>
                </ul></li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%" ><a href='#'>Categorias</a>
                  <ul>
                    <li><%= link_to 'Cadastrar', new_category_path %></li>
                    <li><%= link_to 'Ver todos', categories_path %></li>
                  </ul>
                </li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%">
                  <%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
                
              </nav>
            </div>
          </div>
        </div>
      </div>

		<div class='container-fluid' >
			<ul class='errors'>
				<% @brand.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
			<div class='row'>
				<div class='col-lg-4 col-md-4 col-sm-4 col-xs-4 form-border' align='center' style=' padding-bottom: 1%; float:none; margin: 0 auto;'>
					<%= render 'form', brand: @brand %>
				</div>
			</div>
		</div>
	</body>

app/views/brands/show.html.erb
<body class='bg-new'>
	 <div class='container-fluid'>
        <div class='row' align='center'>    
          <nav class='navbar menu' >
            <ul>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -4%"><a href='#'>Produtos</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_product_path %></li>
                  <li><%= link_to 'Ver todos', products_path %></li>
                </ul>
              </li>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%"><a href='#'>Marcas</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_brand_path %></li>
                  <li><%= link_to 'Ver todos', brands_path %></li>
                </ul></li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%" ><a href='#'>Categorias</a>
                  <ul>
                    <li><%= link_to 'Cadastrar', new_category_path %></li>
                    <li><%= link_to 'Ver todos', categories_path %></li>
                  </ul>
                </li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%">
                  <%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
              </nav>
            </div>
          </div>
        </div>
      </div>

		<div class='container-fluid'>
			<div class='row'>
				<div class=' col-lg-12 ' align='center'>
					<hr>
					<%= image_tag @brand.picture.url(:medium) %>
					<hr>
				</div>
			</div>
		</div>
		<div class='container-fluid'>
			<div class='row'>
				<div class=' col-lg-12 ' align='center' style='padding-bottom: 0.2%;'>
					<strong>Nome:</strong>
					<%= @brand.name %>
				</div>
				<div class=' col-lg-12 ' align='center' style='padding-top: 0.2%;'>
					<%= link_to 'Editar', edit_brand_path(@brand), :class => 'btn btn-warning'
					%> 
					<%= link_to 'Voltar', brands_path, :class => 'btn btn-danger' %>
				</div>
			</div>
		</div>
	</body>