config/routes.rb
Rails.application.routes.draw do
	namespace 'api' do
		namespace 'v1' do
			resources :categories
			resources :brands
			resources :products
		end
	end
devise_for :users
resources :products
resources :brands
resources :categories
resources :users
root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product, :dependent => :delete_all
	acts_as_paranoid
	has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" },
	:path => ':rails_root/public/images/categories/:id-:basename-:style.:extension',
	:url => '/images/categories/:id-:basename-:style.:extension'
	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
	validates :name, presence: true
	validates :picture, attachment_presence: true
	#Search method
	def self.search(search)
		where("name LIKE ?", "%#{search}%") 
	end
	def picture_url
		picture.url(:thumb)
	end
end

app/controllers/api/v1/categories_controller.rb
module Api
	module V1
		class CategoriesController < ApplicationController   
			def index
				categories = Category.order('created_at DESC');
				render json: {status: 'SUCCESS', message:'Objetos carregados', data:categories, }, :methods => [:picture_url] ,status: :ok	
			end
			def destroy
				categories = Category.all
				categories = Category.where(id: params[:id]).first
				if categories.destroy
					redirect_to categories_url
				end
			end
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :index
  before_action :authenticate_user!


  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    if params[:search]
      @categories = Category.search(params[:search]).order("created_at DESC")
    else
      @categories = Category.all.order('created_at DESC')
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :picture, :search)
    end
  end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_edit.html.erb
    <p class='form-p' style='padding-left: 5%'>Atualizar Categoria</p>
    <%= form_with(model: category, local: true, html: { multipart: true }) do |form| %>
    <%= form.label 'Nome:' %>
    <br>
    <%= form.text_field :name, id: :product_name %>
    <br>
    <%= form.label 'Foto:'%> 
    <br>
    <%= form.file_field :picture %>
    <br>
    <div class="wrapper">
      <span class="group-btn">     
        <%= form.submit 'Atualizar Categoria', :class => 'btn btn-success' %>
        <%= link_to 'Voltar', categories_path, :class => 'btn btn-warning' %>
      </div>
    </span>
    <% end %> 

app/views/categories/_form.html.erb
    <p class='form-p' style='padding-left: 5%'>Cadastro Categoria</p>
    <%= form_with(model: category, local: true, html: { multipart: true }) do |form| %>
    <%= form.label 'Nome:' %>
    <br>
    <%= form.text_field :name, id: :product_name %>
    <br>
    <%= form.label 'Foto:'%> 
    <br>
    <%= form.file_field :picture %>
    <br>
    <div class="wrapper">
      <span class="group-btn">     
        <%= form.submit 'Cadastrar Categoria', :class => 'btn btn-success' %>
        <%= link_to 'Voltar', categories_path, :class => 'btn btn-warning' %>
      </div>
    </span>
    <% end %> 

app/views/categories/edit.html.erb
<body class='bg-new'>
 <div class='container-fluid'>
        <div class='row' align='center'>    
          <nav class='navbar menu' >
            <ul>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -4%"><a href='#'>Produtos</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_product_path %></li>
                  <li><%= link_to 'Ver todos', products_path %></li>
                </ul>
              </li>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%"><a href='#'>Marcas</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_brand_path %></li>
                  <li><%= link_to 'Ver todos', brands_path %></li>
                </ul></li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%" ><a href='#'>Categorias</a>
                  <ul>
                    <li><%= link_to 'Cadastrar', new_category_path %></li>
                    <li><%= link_to 'Ver todos', categories_path %></li>
                  </ul>
                </li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%">
                  <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
                  </li>
                
              </nav>
            </div>
          </div>
        </div>
      </div>

	<div class='container-fluid' >
		<ul class='errors'>
			<% @category.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
		<div class='row' style=' margin-left: auto; margin-right: auto'>
			<div class='col-lg-4 col-md-4 form-border' align='center' style=' padding-bottom: 1%; float:none; margin: 0 auto;'>
				<%= render 'edit', category: @category %>
			</div>
		</div>
	</div>
</body>

app/views/categories/index.html.erb
<body >
  <!-- Navbar -->
  <div class='container-fluid'>
    <div class='row' align='center'>    
      <nav class='navbar menu' >
        <ul>
          <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -4%"><a href='#'>Produtos</a>
            <ul>
              <li><%= link_to 'Cadastrar', new_product_path %></li>
              <li><%= link_to 'Ver todos', products_path %></li>
            </ul>
          </li>
          <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%"><a href='#'>Marcas</a>
            <ul>
              <li><%= link_to 'Cadastrar', new_brand_path %></li>
              <li><%= link_to 'Ver todos', brands_path %></li>
            </ul></li>
            <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%" ><a href='#'>Categorias</a>
              <ul>
                <li><%= link_to 'Cadastrar', new_category_path %></li>
                <li><%= link_to 'Ver todos', categories_path %></li>
              </ul>
            </li>
            <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%">
              <%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>

            </nav>
          </div>
        </div>
      </div>
    </div>


    <div class="container-fluid">
      <h2 style='text-align: center'>Categorias</h2>
    </div>
    <!-- Table -->
    <div class="table-responsive" style="width: 70%; margin-left: auto; margin-right: auto;">
      <div ng-controller='ListCategoryCtrl'>
        <div align='center' style='min-width: 70%;'>
         <input type="text" ng-model="agoravai" class='form-control' style='width: 25%; text-align: center' placeholder="Informe o nome ...">
       </div>
       <table class="table table-striped">
        <thead>
          <tr>
            <th>Foto</th>
            <th>Nome</th>
            <th> </th>
          </tr>
        </thead>
        <tbody ng-repeat="categories in category | filter:{name:agoravai}">
          <td><img src='{{categories.picture_url}}'></td>
          <td>{{categories.name}}</td>
          <td>
          <a href='categories/{{categories.id}}' class='btn btn-info'>Ver</a>
          <a data-method='delete' data-confirm='Você tem certeza?' href='/api/v1/categories/{{categories.id}}' class='btn btn-danger'> Deletar </a>
          </td>
        </tbody>
      </table>
    </div>
    <%= link_to 'Nova categoria', new_category_path, :class => 'btn btn-primary' %>
  </div>
</div>
</div>
</div>

app/views/categories/new.html.erb
<body class='bg-new'>
	<div class='container-fluid'>
		<div class='row' align='center'>    
			<nav class='navbar menu' >
				<ul>
					<li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -4%"><a href='#'>Produtos</a>
						<ul >
							<li><%= link_to 'Cadastrar', new_product_path %></li>
							<li><%= link_to 'Ver todos', products_path %></li>
						</ul>
					</li>
					<li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%"><a href='#'>Marcas</a>
						<ul>
							<li><%= link_to 'Cadastrar', new_brand_path %></li>
							<li><%= link_to 'Ver todos', brands_path %></li>
						</ul></li>
						<li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%" ><a href='#'>Categorias</a>
							<ul>
								<li><%= link_to 'Cadastrar', new_category_path %></li>
								<li><%= link_to 'Ver todos', categories_path %></li>
							</ul>
						</li>
						<li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%">
							<%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
							
						</nav>
					</div>
				</div>
			</div>
		</div>

		<div class='container-fluid' >
			<ul class='errors'>
				<% @category.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
			<div class='row' style=' margin-left: auto; margin-right: auto'>
				<div class='col-lg-4 col-md-4 col-xs-4 col-sm-4 form-border' align='center' style=' padding-bottom: 1%; float:none; margin: 0 auto;'>
					<%= render 'form', category: @category %>
				</div>
			</div>
		</div>
	</body>

app/views/categories/show.html.erb
<body class='bg-new'>
 <div class='container-fluid'>
        <div class='row' align='center'>    
          <nav class='navbar menu' >
            <ul>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -4%"><a href='#'>Produtos</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_product_path %></li>
                  <li><%= link_to 'Ver todos', products_path %></li>
                </ul>
              </li>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%"><a href='#'>Marcas</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_brand_path %></li>
                  <li><%= link_to 'Ver todos', brands_path %></li>
                </ul></li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%" ><a href='#'>Categorias</a>
                  <ul>
                    <li><%= link_to 'Cadastrar', new_category_path %></li>
                    <li><%= link_to 'Ver todos', categories_path %></li>
                  </ul>
                </li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%">
                  <%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
                
              </nav>
            </div>
          </div>
        </div>
      </div>

	<div class='container-fluid'>
		<div class='row'>
			<div class=' col-lg-12 ' align='center'>
				<hr>
				<%= image_tag @category.picture.url(:medium) %>
				<hr>
			</div>
		</div>
	</div>
	<div class='container-fluid'>
		<div class='row'>
			<div class=' col-lg-12 ' align='center' style='padding-bottom: 0.2%;'>
				<strong>Nome:</strong>
				<%= @category.name %>
			</div>
			<div class=' col-lg-12 ' align='center' style='padding-top: 0.2%;'>
				<%= link_to 'Editar', edit_category_path(@category), :class => 'btn btn-warning'
				%> 
				<%= link_to 'Voltar', categories_path, :class => 'btn btn-danger' %>
			</div>
		</div>
	</div>
</body>