config/routes.rb
Rails.application.routes.draw do
	namespace 'api' do
		namespace 'v1' do
			resources :categories
			resources :brands
			resources :products
		end
	end
devise_for :users
resources :products
resources :brands
resources :categories
resources :users
root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :brand
	belongs_to :category
	acts_as_paranoid
	has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, 
	:path => ':rails_root/public/images/products/:id-:basename-:style.:extension',
	:url => '/images/products/:id-:basename-:style.:extension'
	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
	validates :name, presence: true
	validates :price, numericality: true
	validates :picture, attachment_presence: true
	#Search method
	def self.search(search)
		where("name LIKE ?", "%#{search}%") 
	end
	def picture_url
		picture.url(:thumb)
	end
end

app/controllers/api/v1/products_controller.rb
module Api
	module V1
		class ProductsController < ApplicationController   
			def index
				product = Product.order('created_at DESC');
				render json: product, include: ['category', 'brand'], :methods => [:picture_url]
			end
			def destroy
				product = Product.all
				product = Product.where(id: params[:id]).first
				if product.destroy
					redirect_to products_url
				end
			end
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_category, only: [:new, :show, :edit, :update, :destroy]
  before_action :set_brand, only: [:new, :show, :edit, :update, :destroy]
  protect_from_forgery except: :index
  before_action :authenticate_user!


  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC")
    else
      @products = Product.all.order('created_at DESC')
    end

  end

  # GET /products/1
  # GET /products/1.json
  def show

  end

  # GET /products/new
  def new
    @product = Product.new

  end

  # GET /products/1/edit
  def edit

  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
    def set_category
      @category = Category.all
    end
    def set_brand
      @brand = Brand.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :price, :brand_id, :category_id, :picture, :search)
    end
  end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_edit.html.erb
      <p class='form-p' style='padding-left: 5%'>Atualizar Produto</p>
      <%= form_with(model: product, local: true, html: { multipart: true }) do |form| %>
      <%= form.label 'Nome:' %>
      <br>
      <%= form.text_field :name, id: :product_name %>
      <br>
      <%= form.label 'Preço:'%>
      <br>
      <%= form.text_field :price, id: :product_price %>
      <br>
      <%= form.label 'Marca:' %>
      <br>
      <%= form.collection_select( :brand_id, Brand.all, :id, :name, {include_blank: true}) %>
      <br>
      <%= form.label 'Categoria:' %>
      <br>
      <%= form.collection_select( :category_id, Category.all, :id, :name, {include_blank: true}) %>
      <br>
      <%= form.label 'Foto:'%> 
      <br>
      <%= form.file_field :picture %>
      <br>
      <div class="wrapper">
        <span class="group-btn">     
          <%= form.submit 'Atualizar Produto', :class => 'btn btn-success' %>
          <%= link_to 'Voltar', products_path, :class => 'btn btn-warning' %>
          <% end %>
        </div>
      </span>
      

app/views/products/_form.html.erb
      <p class='form-p' style='padding-left: 5%'>Cadastro Produto</p>
      <%= form_with(model: product, local: true, html: { multipart: true }) do |form| %>
      <%= form.label 'Nome:' %>
      <br>
      <%= form.text_field :name, id: :product_name %>
      <br>
      <%= form.label 'Preço:'%>
      <br>
      <%= form.text_field :price, id: :product_price %>
      <br>
      <%= form.label 'Marca:' %>
      <br>
      <%= form.collection_select( :brand_id, Brand.all, :id, :name, {include_blank: true}) %>
      <br>
      <%= form.label 'Categoria:' %>
      <br>
      <%= form.collection_select( :category_id, Category.all, :id, :name, {include_blank: true}) %>
      <br>
      <%= form.label 'Foto:'%> 
      <br>
      <%= form.file_field :picture %>
      <br>
      <div class="wrapper">
        <span class="group-btn">     
          <%= form.submit 'Cadastrar Produto', :class => 'btn btn-success' %>
          <%= link_to 'Voltar', products_path, :class => 'btn btn-warning' %>
          <% end %>
        </div>
      </span>
      

app/views/products/edit.html.erb
<body class='bg-new'>
 <div class='container-fluid'>
        <div class='row' align='center'>    
          <nav class='navbar menu' >
            <ul>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -4%"><a href='#'>Produtos</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_product_path %></li>
                  <li><%= link_to 'Ver todos', products_path %></li>
                </ul>
              </li>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%"><a href='#'>Marcas</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_brand_path %></li>
                  <li><%= link_to 'Ver todos', brands_path %></li>
                </ul></li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%" ><a href='#'>Categorias</a>
                  <ul>
                    <li><%= link_to 'Cadastrar', new_category_path %></li>
                    <li><%= link_to 'Ver todos', categories_path %></li>
                  </ul>
                </li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%">
                  <%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
                
              </nav>
            </div>
          </div>
        </div>
      </div>

	<div class='container-fluid'>
		<ul class='errors'>
		<% @product.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
		<div class='row'>
			<div class='col-lg-4 col-md-4 col-sm-4 form-border' align='center' style=' padding-bottom: 1%; float:none; margin: 0 auto;'>
				<%= render 'edit', product: @product %>
			</div>
		</div>
	</div>
</body>

app/views/products/index.html.erb
<!-- Navbar -->
<body >
  <div class='container-fluid'>
    <div class='row' align='center'>    
      <nav class='navbar menu' >
        <ul>
          <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -4%"><a href='#'>Produtos</a>
            <ul>
              <li><%= link_to 'Cadastrar', new_product_path %></li>
              <li><%= link_to 'Ver todos', products_path %></li>
            </ul>
          </li>
          <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%"><a href='#'>Marcas</a>
            <ul>
              <li><%= link_to 'Cadastrar', new_brand_path %></li>
              <li><%= link_to 'Ver todos', brands_path %></li>
            </ul></li>
            <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%" ><a href='#'>Categorias</a>
              <ul>
                <li><%= link_to 'Cadastrar', new_category_path %></li>
                <li><%= link_to 'Ver todos', categories_path %></li>
              </ul>
            </li>
            <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%">
              <%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>

            </nav>
          </div>
        </div>
      </div>
    </div>


    <div class="container-fluid" ng-controller='ListProductCtrl'>
      <h2 style='text-align: center'>Produtos</h2>
    </div>

    <!-- Table -->
    <div class="table-responsive" style="width: 70%; margin-left: auto; margin-right: auto;">
      <div ng-app='myApp' ng-controller='ListProductCtrl'>
        <div align='center' style='min-width: 70%;'>
         <input type="text" ng-model="agoravai" class='form-control' style='width: 25%; text-align: center' placeholder="Informe o nome ...">
       </div>
       <table class="table table-striped">
        <thead>
          <tr>
            <th> Foto </th>
            <th> Nome </th>
            <th> Preço </th>
            <th> Marca </th>
            <th> Categoria </th>
            <th></th>
          </tr>
        </thead>
        <tbody ng-repeat="products in product | filter:{name:agoravai}">
          <td><img src='{{products.picture_url}}'></td>
          <td>{{products.name}}</td>
          <td>{{products.price}}</td>
          <td>{{products.brand.name}}</td>
          <td>{{products.category.name}}</td>
          <td>
            <a href='products/{{products.id}}' class='btn btn-info'>Ver</a>
            <a data-method='delete' data-confirm='Você tem certeza?' href='/api/v1/products/{{products.id}}' class='btn btn-danger'> Deletar </a>
          </td>
        </tbody>
      </table>
    </div>
    <%= link_to 'Novo Produto', new_product_path, :class => 'btn btn-primary' %>
  </div>
</div>
</div>
</div>

</body>

app/views/products/new.html.erb
<body class='bg-new'>
 <div class='container-fluid'>
        <div class='row' align='center'>    
          <nav class='navbar menu' >
            <ul>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -4%"><a href='#'>Produtos</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_product_path %></li>
                  <li><%= link_to 'Ver todos', products_path %></li>
                </ul>
              </li>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%"><a href='#'>Marcas</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_brand_path %></li>
                  <li><%= link_to 'Ver todos', brands_path %></li>
                </ul></li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%" ><a href='#'>Categorias</a>
                  <ul>
                    <li><%= link_to 'Cadastrar', new_category_path %></li>
                    <li><%= link_to 'Ver todos', categories_path %></li>
                  </ul>
                </li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%">
                  <%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
                
              </nav>
            </div>
          </div>
        </div>
      </div>

		<div class='container-fluid' %>
			<ul class='errors'>
				<% @product.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
			<div class='row'>
				<div class='col-xs-4 col-4 col-lg-4 col-md-4 col-sm-4 form-border' align='center' style=' padding-bottom: 1%; float:none; margin: 0 auto;'>
					<%= render 'form', product: @product %>
				</div>
			</div>
		</div>
	</body>

app/views/products/show.html.erb
<body class='bg-new'>
 <div class='container-fluid'>
        <div class='row' align='center'>    
          <nav class='navbar menu' >
            <ul>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -4%"><a href='#'>Produtos</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_product_path %></li>
                  <li><%= link_to 'Ver todos', products_path %></li>
                </ul>
              </li>
              <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%"><a href='#'>Marcas</a>
                <ul>
                  <li><%= link_to 'Cadastrar', new_brand_path %></li>
                  <li><%= link_to 'Ver todos', brands_path %></li>
                </ul></li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%" ><a href='#'>Categorias</a>
                  <ul>
                    <li><%= link_to 'Cadastrar', new_category_path %></li>
                    <li><%= link_to 'Ver todos', categories_path %></li>
                  </ul>
                </li>
                <li class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-2" style="margin-left: -2%">
                  <%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
                
              </nav>
            </div>
          </div>
        </div>
      </div>

	<div class='container-fluid'>
		<div class='row'>
			<div class=' col-lg-12 ' align='center'>
				<hr>
				<%= image_tag @product.picture.url(:medium) %>
				<hr>
			</div>
		</div>
	</div>
	<div class='container-fluid'>
		<div class='row'>
			<div class=' col-lg-12 ' align='center' style='padding-bottom: 0.2%;'>
				<strong>Nome:</strong>
				<%= @product.name %>
			</div>
			<div class=' col-lg-12 ' align='center' style='padding-bottom: 0.2%;'>
				<strong>Preço:</strong>
				<%= @product.price %>
			</div>
			<div class=' col-lg-12 ' align='center' style='padding-bottom: 0.2%;'>
				<strong>Marca:</strong>
				<%= @product.brand.name %>
			</div>
			<div class=' col-lg-12 ' align='center' style='padding-bottom: 0.2%;'>
				<strong>Categoria:</strong>
				<%= @product.category.name %>
			</div>
			<div class=' col-lg-12 ' align='center' style='padding-top: 0.2%;'>
				<%= link_to 'Editar', edit_product_path(@product), :class => 'btn btn-warning'
				%> 
				<%= link_to 'Voltar', products_path, :class => 'btn btn-danger' %>
			</div>
		</div>
	</div>
</body>